### ISSUE TITLE
请求参数污染

### ISSUE THREAD

**Issue by supwlz** [qifengzhang007/GinSkeleton#1]
多次请求，当后面请求参数没有把前面覆盖了，取到的就是前面的内容。验证器那里也是这样
`func (u *Users) Login(context *gin.Context) {
	name := context.GetString(Consts.Validator_Prefix + "name")
	pass := context.GetString(Consts.Validator_Prefix + "pass")
	name2 := context.PostForm("name")
	pass2 := context.PostForm("pass")
	data := gin.H{
		"name":name,
		"pass":pass,
		"name2":name2,
		"pass2":pass2,
	}
	Response.ReturnJson(context, http.StatusOK, Consts.Curd_Login_Fail_Code, Consts.Curd_Login_Fail_Msg, data)
}
`
![image](https://user-images.githubusercontent.com/24469800/81774597-8bc8bc00-951d-11ea-80dc-fb17e9f8cdff.png)

**Comment by qifengzhang007** [comment]
3q，问题已经定位，参数验证器在容器进行了全局注册，调用后没有及时清除相关字段值。
17:43， 相关问题已经修复，请及时更新版本。
感谢反馈。
